#server:
#  port: 88
#
## 应用名称
#spring:
#  application:
#    name: mall-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #todo 写自己的nacos
#    gateway:
#      routes:
#        # 精确的路由要放在/api的admin_route上面
#        - id: product_route
#          uri: lb://mall-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: product_route
#          uri: lb://mall-search
#          predicates:
#            - Path=/api/search/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: coupon_route
#          uri: lb://mall-coupon
#          predicates:
#            - Path=/api/coupon/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: order_route
#          uri: lb://mall-order
#          predicates:
#            - Path=/api/order/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: member_route
#          uri: lb://mall-member
#          predicates:
#            - Path=/api/member/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: ware_route
#          uri: lb://mall-ware
#          predicates:
#            - Path=/api/ware/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: third_party_route
#          uri: lb://mall-thirdparty
#          predicates:
#            - Path=/api/thirdparty/**
#          filters:
#            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
#            - AddRequestHeader=source,dashboard # 添加请求头
#
#        - id: mall_index_route
#          uri: lb://mall-product
#          predicates:
#            - Host=mall-yeye.com,item.mall-yeye.com
#
#        - id: mall_search_route
#          uri: lb://mall-search
#          predicates:
#            - Host=search.mall-yeye.com
#
#        - id: mall_auth_route
#          uri: lb://mall-auth-server
#          predicates:
#            - Host=auth.mall-yeye.com
#
#        - id: mall_cart_route
#          uri: lb://mall-cart
#          predicates:
#            - Host=cart.mall-yeye.com
#
#        - id: mall_order_route
#          uri: lb://mall-order
#          predicates:
#            - Host=order.mall-yeye.com
#
#        - id: mall_member_route
#          uri: lb://mall-member
#          predicates:
#            - Host=member.mall-yeye.com
#
#        - id: mall_seckill_route
#          uri: lb://mall-seckill
#          predicates:
#            - Host=seckill.mall-yeye.com
#
#            #路径重写。逗号左边是原路径，右边是重写后的路径
#            # 默认规则， 请求过来：http://search.mall-yeye.com   转发-->  http://mall-search --> Nacos(127.0.0.1:12000)
#
