#spring:
#  application:
#    name: mall-cart
#  thymeleaf:
#    cache: false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #todo 写自己的nacos
#  redis:
#    host: 127.0.0.1 #todo 写自己的redis地址
#    port: 6379
#    password:  #todo 写自己的redis密码，没有不写
#  session:
#    store-type: redis
#server:
#  port: 40000
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 60000
#        readTimeout: 60000
#
#mall:
#  thread:
#    core-size: 20
#    max-size: 200
#    keep-alive-time: 10
#    time-unit: seconds