## 应用名称
#spring.application.name: mall-order
## 应用服务 WEB 访问端口
#server.port: 9000
#spring:
#  datasource:
#    username: root
#    password: root #todo 写自己的mysql 账号密码和地址
#    url: jdbc:mysql://127.0.0.1:3306/mall_oms?useUniapplication.ymlcode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driverClassName: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 10000
#      validation-timeout: 3000
#      idle-timeout: 60000
#      login-timeout: 5
#      max-lifetime: 60000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      read-only: false
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #todo 写自己的nacos
#    alibaba:
#      seata:
#        tx-service-group: mall-order-fescar-service-group
#  rabbitmq:
#    host: 127.0.0.1 #todo 写自己的rabbitmq地址
#    username: guest
#    password: guest
#    port: 5672
#    virtual-host: /
#    # 到达确认
#    publisher-confirms: true
#    # 到达queue确认
#    publisher-returns: true
#    # 异步确认
#    template:
#      mandatory: true
#    # 手动确认消息消费
#    listener:
#      simple:
#        acknowledge-mode: manual
#  thymeleaf:
#    cache: false
#  redis:
#    host: 127.0.0.1 #todo 写自己的redis地址
#    port: 6379
#    password:  #todo 写自己的redis密码，没有不写
#  session:
#    store-type: redis
#    timeout: 30m
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss
#mybatis-plus:
#  configuration:
#    #数据库下划线和实体类驼峰统一
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    global-config:
#      db-config:
#        id-type: auto
#      banner: false
#
#  #告诉mp，sql映射文件的位置，默认值classpath*:/mapper/**/*.xml。
#  #  classpath表示只引用现在模块的类路径。classpath*表示不止引用现在模块的类路径，还包括依赖jar包的类路径
#  mapper-locations: classpath:/mapper/**/*.xml
#
#
#mall:
#  thread:
#    core-size: 20
#    max-size: 200
#    keep-alive-time: 10
#    time-unit: seconds
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 60000
#        readTimeout: 60000
#
#alipay:
#  app_id: 1111111111111111 #todo 全部写自己的支付宝沙箱
#  notify_url: http://xxx/order/pay/alipay/success #todo xxx替换为自己的内网穿透地址，用于接收支付宝回调
#  return_url: http://member.mall-yeye.com/memberOrderList.html
#  sign_type: RSA2
#  charset: utf-8
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do
#  timeout_express: 5m